FROM almalinux:9
RUN  dnf install nginx -y
CMD ["nginx","-g","daemon off;"]

# FROM RUN  we can use how ever we want here the code in run is same a above except cmd
# CMD ["nginx" "-g" "daemon off ;"]